# configuration file for trace_source
# https://github.com/toml-lang/toml
#

output_dir = "output/limassol/"
plot_dir = "plots/limassol"
traj_dir = "trajectories/limassol/"
partposit_dir = "flexpart_partposit/limassol/"

geonames = 'standard'

[time]
    #begin = '2018-03-14_00'
    #end = '2018-03-25_00'
    begin = '2015-09-09_00'
    end = '2015-09-14_00'
    # time step for which trajectories are calculated
    step = 3
    # duration of each trajectory
    tr_duration = -240

[flexpart]
    no_particles = 500
    rel_before_minutes = 5
    rel_after_minutes = 0
    rel_pm_height = 200
    species = 24

[plotmap]
    maptype = 'miller'
    timeinterval = 6
    heights = [1500.0, 3000.0, 4500.0, 6000.0]
    #heights = [1500.0, 3000.0, 4500.0, 6000.0, 8000.0, 10000.0, 11000.0]
    #heights = [8000.0, 10000.0, 11000.0]
    bounds = [-120, 80, 0, 85]
    centerlon = -10
    # heights = [8000.0, 10000.0, 11000.0]
    #bounds = [-179.9, 180.0, -75.0, 0.0]
    #bounds = [-120, 80, 0, 85]
    # detailed map for paper
    #bounds = [-100, -50, -65, -20]

[height]
    top = 12000
    base = 500
    interval = 500
    plottop = 10250
    # 'md' mixing depth, '2.0' in km without
    reception = ['md', '2.0', '5.0']

[station]
    name = 'Limassol, Cyprus'
    short_name = 'limassol'
    lat = 34.677
    lon = 33.038
    altitude = 10
